### ISSUE TITLE
Creating issues on the github app is broken

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-project#30]
### Provide a general description of the issue or problem.

Not sure what is going on but it looks like when trying to create a new issue it tries to open a webpage and gets a 404 error. Maybe this has to do with the template we are using.

**Comment by ehsteve** [comment]
This is also true of the sunpy repo.

**Comment by Cadair** [comment]
:shrug: sounds like a github bug to me?

**Comment by Cadair** [comment]
https://github.com/orgs/community/discussions/15248
